DROP TABLE IF EXISTS task;

CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    taskname TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);